---
language: python
services: docker
jobs:
  include:
    - name: "(Debian/Ubuntu) Test config templates"
      env:
        scenario: default
    - name: "(Alpine) Test config templates"
      env:
        scenario: default_alpine
    - name: "(CentOS) Test config templates"
      env:
        scenario: default_centos
    - name: "(Debian/Ubuntu) Install Modules"
      env:
        scenario: module
    - name: "(Alpine) Install Modules"
      env:
        scenario: module_alpine
    - name: "(CentOS) Install Modules"
      env:
        scenario: module_centos
    - name: "(Debian/Ubuntu) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push
    - name: "(Alpine) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_alpine
    - name: "(CentOS) Install Stable Branch and Push Configuration"
      env:
        scenario: stable_push_centos
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
  - pip install ansible==2.9.13
  - pip install ansible-lint==4.3.3
  - pip install molecule==3.0.8
  - pip install docker==4.3.1
script:
  - molecule --version
  - ansible --version
  - travis_wait 50 molecule test -s $scenario
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
