---
- name: Converge
  hosts: all
  tasks:
    - name: Configure NGINX
      include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true

        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          conf_file_name: nginx.conf
          conf_file_location: /etc/nginx/
          modules:
            - modules/ngx_http_app_protect_module.so
          user: nginx
          worker_processes: auto
          pid: /var/run/nginx.pid
          error_log:
            location: /var/log/nginx/error.log
            level: warn
          worker_connections: 1024
          http_enable: true
          http_settings:
            app_protect_global:
              physical_memory_util_thresholds:
                high: 100
                low: 100
              cpu_thresholds:
                high: 100
                low: 100
              failure_mode_action: pass
              cookie_seed: testseed
              compressed_requests_action: drop
            default_type: application/octet-stream
            access_log_format:
              - name: main
                format: |
                  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"'
            access_log_location:
              - name: main
                location: /var/log/nginx/access.log
            keepalive_timeout: 65
            cache: false
            rate_limit: false
            keyval: false
            server_tokens: "off"
          sub_filter:
            last_modified: false
            once: true
          http_global_autoindex: false
          custom_options:
            - master_process on;
          http_custom_options:
            - aio off;
          http_custom_includes:
            - "/etc/nginx/sites-enabled/*.conf"
          events_custom_options:
            - accept_mutex off;
          stream_enable: true

        nginx_config_rest_api_enable: true
        nginx_config_rest_api_write: false
        nginx_config_rest_api_access_log: false
        nginx_config_rest_api_dashboard: false

        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - ip: 0.0.0.0
                    port: 80
                    opts:
                      - default_server
                  - ip: 0.0.0.0
                    port: 443
                    ssl: false
                    opts:
                      - default_server
                  - ip: "[::]"
                    port: 80
                    opts:
                      - default_server
                  - ip: "[::]"
                    port: 443
                    ssl: false
                    opts:
                      - default_server
                server_name: localhost
                app_protect:
                  enable: true
                  policy_file: /etc/nginx/app-protect-security-policy.json
                http_error_pages:
                  404: /404.html
                error_page: /usr/share/nginx/html
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                client_max_body_size: 512k
                proxy_hide_header:
                  - X-Powered-By
                add_headers:
                  strict_transport_security:
                    name: Strict-Transport-Security
                    value: max-age=15768000; includeSubDomains
                    always: true
                sub_filter:
                  last_modified: false
                  once: true
                locations:
                  - location: /
                    app_protect:
                      enable: true
                      policy_file: /etc/nginx/app-protect-security-policy.json
                    proxy_hide_header:
                      - X-Powered-By
                    add_headers:
                      strict_transport_security:
                        name: Strict-Transport-Security
                        value: max-age=15768000; includeSubDomains
                        always: true
                      another_header:
                        name: Fancy-New-Header-To-Test
                        value: testing=true
                        always: false
                    rewrites:
                      - (.*).html(.*) $1$2
                    proxy_pass: http://frontend_servers/
                    proxy_cache: frontend_proxy_cache
                    proxy_cache_valid:
                      - code: 200
                        time: 10m
                      - code: 301
                        time: 1m
                    proxy_temp_path:
                      path: /var/cache/nginx/proxy/frontend/temp
                    proxy_cache_lock: false
                    proxy_cache_min_uses: 3
                    proxy_cache_revalidate: false
                    proxy_cache_use_stale:
                      - http_403
                      - http_404
                    proxy_ignore_headers:
                      - Vary
                      - Cache-Control
                    proxy_redirect: false
                    proxy_set_header:
                      header_host:
                        name: Host
                        value: $host
                      header_x_real_ip:
                        name: X-Real-IP
                        value: $remote_addr
                      header_x_forwarded_for:
                        name: X-Forwarded-For
                        value: $proxy_add_x_forwarded_for
                      header_x_forwarded_proto:
                        name: X-Forwarded-Proto
                        value: $scheme
                    proxy_buffering: false
                    client_max_body_size: 5m
                    sub_filter:
                      last_modified: false
                      once: true
                  - location: /backend
                    proxy_pass: http://backend_servers/
                    proxy_cache: backend_proxy_cache
                    proxy_cache_valid:
                      - time: 10m
                    proxy_temp_path:
                      path: /var/cache/nginx/proxy/backend/temp
                    proxy_cache_lock: true
                    proxy_cache_min_uses: 2
                    proxy_cache_revalidate: true
                    proxy_cache_use_stale:
                      - http_500
                      - http_502
                      - http_503
                    proxy_redirect: default
                    proxy_set_header:
                      header_host:
                        name: Host
                        value: $host
                      header_x_real_ip:
                        name: X-Real-IP
                        value: $remote_addr
                      header_x_forwarded_for:
                        name: X-Forwarded-For
                        value: $proxy_add_x_forwarded_for
                      header_x_forwarded_proto:
                        name: X-Forwarded-Proto
                        value: $scheme
                    proxy_cookie_path:
                      path: /web/
                      replacement: /
                returns:
                  return301:
                    location: ^~ /old-path
                    code: 301
                    value: http://$host/new-path
            proxy_cache:
              proxy_cache_path:
                - path: /var/cache/nginx/proxy/frontend
                  keys_zone:
                    name: frontend_proxy_cache
                    size: 5m
                  levels: "1:2"
                  max_size: 5g
                  inactive: 30m
                  use_temp_path: true
                - path: /var/cache/nginx/proxy/backend
                  keys_zone:
                    name: backend_proxy_cache
                    size: 10m
                  levels: "1:2"
                  max_size: 10g
                  inactive: 60m
                  use_temp_path: true
              proxy_temp_path:
                path: /var/cache/nginx/proxy/temp
              proxy_cache_lock: true
              proxy_cache_min_uses: 5
              proxy_cache_revalidate: true
              proxy_cache_use_stale:
                - error
                - timeout
              proxy_ignore_headers:
                - Expires
            upstreams:
              - name: frontend_servers
                zone:
                  name: frontend_mem_zone
                  size: 64k
                least_time:
                  response: last_byte
                  inflight: false
                ntlm: true
                queue:
                  number: 10
                  timeout: 60s
                keepalive: 32
                keepalive_requests: 100
                keepalive_timeout: 60s
                sticky_route:
                  - $cookie_jsessionid
                  - $request_uri
                servers:
                  - address: 0.0.0.0:8081
              - name: backend_servers
                zone:
                  name: backend_mem_zone
                  size: 64k
                random:
                  two: true
                  method: least_time=last_byte
                sticky_learn:
                  create:
                    - $upstream_cookie_example_cookie
                    - $upstream_cookie_example_biscuit
                  lookup:
                    - $cookie_examplecookie
                  zone:
                    name: client_sessions
                    size: 1m
                  timeout: 10m
                  header: false
                  sync: false
                resolver:
                  address:
                    - 127.0.0.1
                  valid: 30s
                  ipv6: false
                  status_zone: backend_mem_zone
                resolver_timeout: 30s
                servers:
                  - address: 0.0.0.0:8082
                    weight: 1
                  - address: unix:/var/run/control.unit.sock
                    weight: 1
                  - address: 0.0.0.0:8083
                    down: true
                  - address: example.com
                    weight: 1
                    max_conns: 0
                    max_fails: 1
                    fail_timeout: 10s
                    backup: false
                    down: false
                    resolve: true
                    route: cookie
                    service: http
                    slow_start: 0s
                    drain: false
          - template_file: http/default.conf.j2
            conf_file_name: frontend_default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - port: 8081
                    opts: []
                server_name: localhost
                error_page: /usr/share/nginx/html
                access_log: "off"
                autoindex: false
                sub_filter:
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
                  last_modified: false
                  once: false
                  types: "text/html"
                locations:
                  - location: /
                    proxy_hide_header:
                      - X-Powered-By
                    root: /usr/share/nginx/html
                    index: frontend_index.html
                    autoindex: false
                http_demo_conf: false
          - template_file: http/default.conf.j2
            conf_file_name: backend_default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - port: 8082
                    opts: []
                server_name: localhost
                error_page: /usr/share/nginx/html
                autoindex: false
                sub_filter:
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
                  last_modified: false
                  once: false
                locations:
                  - location: /
                    root: /usr/share/nginx/html
                    index: backend_index.html
                    autoindex: false
                    allows:
                      - 192.168.1.0/24
                    denies:
                      - all
                  - location: ~ \.php$
                    root: /usr/share/nginx/html
                    autoindex: false
                    custom_options:
                      - fastcgi_split_path_info ^(.+\.php)(/.+)$;
                      - fastcgi_pass unix:/run/php/php7.2-fpm.sock;
                      - fastcgi_index index.php;
                      - include fastcgi_params;
                      - fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                http_demo_conf: false

        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            html_file_name: frontend_index.html
            html_file_location: /usr/share/nginx/html
            web_server_name: Frontend
          - template_file: www/index.html.j2
            html_file_name: backend_index.html
            html_file_location: /usr/share/nginx/html
            web_server_name: Backend

        nginx_config_stream_template_enable: true
        nginx_config_stream_template:
          - template_file: stream/default.conf.j2
            conf_file_name: stream_default.conf
            conf_file_location: /etc/nginx/conf.d/stream
            network_streams:
              - listen:
                  - ip: 0.0.0.0
                    port: 9090
                    opts:
                      - udp
                proxy_pass: backend
                proxy_timeout: 3s
                proxy_connect_timeout: 1s
                proxy_protocol: false
                health_check_plus: false
            upstreams:
              - name: backend
                lb_method: least_conn
                zone_name: backend
                zone_size: 64k
                sticky_cookie: false
                servers:
                  - address: 0.0.0.0
                    port: 9091
                    weight: 1
                    health_check: max_fails=1 fail_timeout=10s
                  - address: 0.0.0.0
                    port: 9092
                    down: true
                  - address: 0.0.0.0
                    port: 9093
                    backup: true
