---
- name: "Print NGINX config"
  debug:
    msg: "Printing NGINX config"
  when: nginx_config_debug_tasks | bool

- name: "Register NGINX config"
  command: nginx -T
  changed_when: false
  register: nginx_configuration

- name: "Print NGINX config"
  debug:
    var: nginx_configuration.stdout_lines
