---
- name: (DEPRECATED) Upload NGINX main config
  block:
    - name: (DEPRECATED) Ensure NGINX main directory exists
      file:
        path: "{{ nginx_config_main_upload_dest | default('/etc/nginx/') }}"
        state: directory
        mode: 0755

    - name: (DEPRECATED) Upload NGINX main config file
      copy:
        src: "{{ nginx_config_main_upload_src | default('conf/nginx.conf') }}"
        dest: "{{ nginx_config_main_upload_dest | default('/etc/nginx') }}"
        backup: true
        mode: 0644
      notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_main_upload_enable | bool

- name: (DEPRECATED) Upload NGINX HTTP config
  block:
    - name: (DEPRECATED) Ensure NGINX HTTP directory exists
      file:
        path: "{{ nginx_config_http_upload_dest | default('/etc/nginx/conf.d/') }}"
        state: directory
        mode: 0755

    - name: (DEPRECATED) Upload NGINX HTTP config files
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_config_http_upload_dest | default('/etc/nginx/conf.d/') }}"
        backup: true
        mode: 0644
      with_fileglob: "{{ nginx_config_http_upload_src }}"
      notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_http_upload_enable | bool

- name: (DEPRECATED) Upload NGINX stream config
  block:
    - name: (DEPRECATED) Ensure NGINX stream directory exists
      file:
        path: "{{ nginx_config_stream_upload_dest | default('/etc/nginx/conf.d/') }}"
        state: directory
        mode: 0755

    - name: (DEPRECATED) Upload NGINX stream config files
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_config_stream_upload_dest | default('/etc/nginx/conf.d/') }}"
        backup: true
        mode: 0644
      with_fileglob: "{{ nginx_config_stream_upload_src }}"
      notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_stream_upload_enable | bool

- name: Upload NGINX config snippets
  block:
    - name: Ensure NGINX config snippet directories exist
      file:
        path: "{{ item.dest | dirname if item.dest.endswith('.conf') else item.dest | default('/etc/nginx') }}"
        state: directory
        mode: 0755
      loop: "{{ nginx_config_upload }}"

    - name: Upload NGINX config snippet files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/etc/nginx/') }}"
        backup: true
        mode: 0644
      loop: "{{ nginx_config_upload }}"
      notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_upload_enable | bool

- name: Upload HTML files
  block:
    - name: Ensure HTML directory exists
      file:
        path: "{{ item.dest | dirname if item.dest.endswith('.html') else item.dest | default('/usr/share/nginx/html') }}"
        state: directory
        mode: 0755
      loop: "{{ nginx_config_upload_html }}"

    - name: Upload HTML files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/usr/share/nginx/html') }}"
        backup: true
        mode: 0644
      loop: "{{ nginx_config_upload_html }}"
      notify: (Handler - NGINX Config) Run NGINX
  when: nginx_config_upload_html_enable | bool

- name: Upload NGINX SSL certificates and keys
  block:
    - name: Ensure SSL certificate and key directories exist
      file:
        path: "{{ item.dest }}"
        state: directory
        mode: 0755
      loop: "{{ nginx_config_upload_ssl_crt +  nginx_config_upload_ssl_key }}"

    - name: Upload NGINX SSL certificates
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/etc/ssl/certs') }}"
        backup: true
        mode: 0640
      loop: "{{ nginx_config_upload_ssl_crt }}"

    - name: Upload NGINX SSL keys
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest | default('/etc/ssl/private') }}"
        backup: true
        mode: 0640
      loop: "{{ nginx_config_upload_ssl_key }}"
      no_log: true
  when: nginx_config_upload_ssl_enable | bool
