---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 10.4.0
  - name: community.crypto
    version: 2.26.0
  - name: community.docker
    version: 4.5.1
