---
- name: "(Handler) Check NGINX"
  command: "nginx -t"
  changed_when: false

- name: "(Handler: All OSs) Run NGINX"
  block:
    - name: "(Handler) Start NGINX"
      service:
        name: nginx
        state: started
        enabled: true
      notify: "(Handler) Check NGINX"
      listen: "(Handler) Reload NGINX config"

    - name: "(Handler) Reload NGINX"
      command: "nginx -s reload"
      changed_when: false
      listen: "(Handler) Reload NGINX config"
  when:
    - nginx_config_start | bool
    - not ansible_check_mode | bool
