---
- name: Prepare
  hosts: all
  tasks:
    - name: Install NGINX
      include_role:
        name: nginxinc.nginx
      vars:
        nginx_modules:
          - njs

    - name: Create mock NGINX configuration file
      file:
        path: /etc/nginx/conf.d/mock.conf
        state: touch
        mode: 0644
