---
- name: Converge
  hosts: all
  tasks:
    - name: Configure NGINX
      include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true

        nginx_config_selinux: true
        nginx_config_selinux_tcp_ports:
          - 80

        nginx_config_upload_ssl_enable: true
        nginx_config_upload_ssl_crt:
          - src: ../common/files/ssl/molecule.crt
            dest: /etc/ssl/certs
        nginx_config_upload_ssl_key:
          - src: ../common/files/ssl/molecule.key
            dest: /etc/ssl/private

        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          conf_file_name: nginx.conf
          conf_file_location: /etc/nginx/
          modules:
            - modules/ngx_http_js_module.so
          user: nginx
          worker_processes: auto
          pid: /var/run/nginx.pid
          error_log:
            location: /var/log/nginx/error.log
            level: warn
          worker_connections: 1024
          http_enable: true
          http_settings:
            grpc_global:
              bind:
                address: $remote_addr
                transparent: false
              buffer_size: 4k
              connect_timeout: 60s
              hide_header:
                - X-Accel-Redirect
              ignore_headers:
                - X-Accel-Redirect
              intercept_errors: false
              next_upstream:
                - timeout
              next_upstream_timeout: 0
              next_upstream_tries: 0
              pass_header:
                - X-Accel-Charset
              read_timeout: 60s
              send_timeout: 60s
              set_header:
                - field: Accept-Encoding
                  value: '""'
              socket_keepalive: false
            gzip:
              enable: true
              buffers:
                number: 32
                size: 4k
              comp_level: 1
              disable:
                - '"msie6"'
              http_version: 1.1
              min_length: 20
              proxied:
                - expired
              types:
                - text/html
              vary: false
            default_type: application/octet-stream
            access_log_format:
              - name: main
                format: |
                  '$remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"'
            access_log_location:
              - name: main
                location: /var/log/nginx/access.log
            keepalive_timeout: 65
            cache: false
            rate_limit: false
            keyval: false
            server_tokens: "off"
            server_names_hash_bucket_size: 64
            server_names_hash_max_size: 512
          sub_filter:
            last_modified: false
            once: true
          http_global_autoindex: false
          custom_options:
            - master_process on;
          http_custom_options:
            - aio off;
          http_custom_includes:
            - "/etc/nginx/sites-enabled/*.conf"
          events_custom_options:
            - accept_mutex off;
          stream_enable: true

        nginx_config_status_enable: true
        nginx_config_status_port: 8080
        nginx_config_status_access_log:
          location: /var/log/nginx/access.log
          name: main

        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - ip: 0.0.0.0
                    port: 80
                    opts:
                      - default_server
                  - ip: 0.0.0.0
                    port: 443
                    ssl: false
                    opts:
                      - default_server
                  - ip: "[::]"
                    port: 80
                    opts:
                      - default_server
                  - ip: "[::]"
                    port: 443
                    ssl: false
                    opts:
                      - default_server
                server_name: localhost
                http_error_pages:
                  404: /404.html
                error_page: /usr/share/nginx/html
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                client_max_body_size: 512k
                add_headers:
                  strict_transport_security:
                    name: Strict-Transport-Security
                    value: max-age=15768000; includeSubDomains
                    always: true
                sub_filter:
                  last_modified: false
                  once: true
                ssl:
                  buffer_size: 16k
                  certificate: /etc/ssl/certs/molecule.crt
                  certificate_key: /etc/ssl/private/molecule.key
                  ciphers:
                    - HIGH
                    - "!aNull"
                    - "!MD5"
                  conf_command: Protocol TLSv1.2
                  early_data: false
                  ecdh_curve: auto
                  ocsp: false
                  ocsp_cache:
                    name: cache1
                    size: 1m
                  ocsp_responder: false
                  prefer_server_ciphers: false
                  protocols:
                    - TLSv1
                    - TLSv1.1
                    - TLSv1.2
                    # - TLSv1.3
                  reject_handshake: false
                  session_cache:
                    builtin:
                      enable: true
                      size: 20480
                  session_tickets: true
                  session_timeout: 5m
                  stapling: false
                  stapling_verify: false
                  verify_client: false
                  verify_depth: 1
                locations:
                  - location: /
                    grpc:
                      pass: localhost:9000
                    add_headers:
                      strict_transport_security:
                        name: Strict-Transport-Security
                        value: max-age=15768000; includeSubDomains
                        always: true
                      another_header:
                        name: Fancy-New-Header-To-Test
                        value: testing=true
                        always: false
                    rewrites:
                      - (.*).html(.*) $1$2
                    proxy_pass: http://frontend_servers/
                    proxy:
                      bind: false
                      buffer_size: 4k
                      buffering: true
                      buffers:
                        number: 8
                        size: 4k
                      busy_buffers_size: 8k
                      cache: false
                      cache_background_update: false
                      cache_bypass:
                        - - $cookie_nocache
                          - $arg_nocache$arg_comment
                        - $cookie_test
                      cache_convert_head: true
                      cache_key: $scheme$proxy_host$request_uri
                      cache_lock: false
                      cache_lock_age: 5s
                      cache_lock_timeout: 5s
                      cache_max_range_offset: 1
                      cache_methods:
                        - GET
                        - HEAD
                      cache_min_uses: 1
                      cache_revalidate: false
                      cache_use_stale: false
                      cache_valid:
                        - code: 200
                          time: 10m
                        - code:
                            - 201
                            - 202
                          time: 10m
                        - time: 1m
                      connect_timeout: 60s
                      cookie_domain:
                        - domain: localhost
                          replacement: example.com
                      cookie_flags: false
                      cookie_path: false
                      force_ranges: false
                      headers_hash_bucket_size: 64
                      headers_hash_max_size: 512
                      hide_header:
                        - Date
                        - X-Accel-Redirect
                      http_version: 1.1
                      ignore_client_abort: false
                      ignore_headers:
                        - X-Accel-Redirect
                      intercept_errors: false
                      limit_rate: 0
                      max_temp_file_size: 1024m
                      method: GET
                      next_upstream:
                        - error
                        - timeout
                      next_upstream_timeout: 0
                      next_upstream_tries: 0
                      no_cache:
                        - $cookie_nocache
                        - $arg_nocache$arg_comment
                      pass_header:
                        - Date
                        - X-Accel-Redirect
                      pass_request_body: false
                      pass_request_headers: true
                      read_timeout: 60s
                      redirect: false
                      request_buffering: false
                      # send_lowat: 0  # not supported on linux
                      send_timeout: 60s
                      set_body: body
                      set_header:
                        - field: Host
                          value: $proxy_host
                        - field: Connection
                          value: close
                      socket_keepalive: false
                      store: false
                      store_access:
                        user: rw
                        group: rw
                        all: r
                      temp_file_write_size: 8k
                      temp_path:
                        path: /var/cache/nginx/proxy
                        level: 2
                    client_max_body_size: 5m
                    sub_filter:
                      last_modified: false
                      once: true
                  - location: /backend
                    proxy_pass: http://backend_servers/
                    proxy:
                      set_header:
                        - field: Host
                          value: $host
                        - field: X-Real-IP
                          value: $remote_addr
                        - field: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        - field: X-Forwarded-Proto
                          value: $scheme
                returns:
                  return301:
                    location: ^~ /old-path
                    code: 301
                    value: http://$host/new-path
            proxy_cache_path:
              - path: /var/cache/nginx/proxy/frontend
                levels: "1:1"
                use_temp_path: false
                inactive: 10m
                keys_zone:
                  name: frontend_proxy_cache
                  size: 10m
                max_size: 2g
                min_free: 1g
                manager_files: 100
                manager_sleep: 500ms
                manager_threshold: 200ms
                loader_files: 100
                loader_sleep: 50ms
                loader_threshold: 200ms
                # purger: false  # NGINX Plus only
                # purger_files: 10
                # purger_sleep: 50ms
                # purger_threshold: 50ms
              - path: /var/cache/nginx/proxy/backend
                levels: "1:2"
                use_temp_path: true
                keys_zone:
                  name: backend_proxy_cache
                  size: 10m
                inactive: 60m
                max_size: 10g
            upstreams:
              - name: frontend_servers
                zone:
                  name: frontend_mem_zone
                  size: 64k
                least_conn: true
                keepalive: 32
                keepalive_requests: 100
                keepalive_timeout: 60s
                servers:
                  - address: 0.0.0.0:8081
                    weight: 1
                    max_fails: 3
                    fail_timeout: 5s
              - name: backend_servers
                zone:
                  name: backend_mem_zone
                  size: 64k
                least_conn: true
                servers:
                  - address: 0.0.0.0:8082
                    weight: 1
                    max_fails: 3
                    fail_timeout: 5s
                  - address: unix:/var/run/control.unit.sock
                    weight: 1
                    max_fails: 3
                    fail_timeout: 5s
                  - address: 0.0.0.0:8083
                    down: true
                  - address: 0.0.0.0:8084
                    backup: true
          - template_file: http/default.conf.j2
            conf_file_name: frontend_default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - port: 8081
                    opts: []
                server_name: localhost
                error_page: /usr/share/nginx/html
                access_log: "off"
                autoindex: false
                sub_filter:
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
                  last_modified: false
                  once: false
                  types: "text/html"
                locations:
                  - location: /
                    root: /usr/share/nginx/html
                    index: frontend_index.html
                    autoindex: false
                http_demo_conf: false
          - template_file: http/default.conf.j2
            conf_file_name: backend_default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              - listen:
                  - port: 8082
                    opts: []
                server_name: localhost
                error_page: /usr/share/nginx/html
                autoindex: false
                sub_filter:
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
                  last_modified: false
                  once: false
                locations:
                  - location: /
                    root: /usr/share/nginx/html
                    index: backend_index.html
                    autoindex: false
                    allows:
                      - 192.168.1.0/24
                    denies:
                      - all
                  - location: ~ \.php$
                    root: /usr/share/nginx/html
                    autoindex: false
                    custom_options:
                      - fastcgi_split_path_info ^(.+\.php)(/.+)$;
                      - fastcgi_pass unix:/run/php/php7.2-fpm.sock;
                      - fastcgi_index index.php;
                      - include fastcgi_params;
                      - fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                http_demo_conf: false

        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            html_file_name: frontend_index.html
            html_file_location: /usr/share/nginx/html
            web_server_name: Frontend
          - template_file: www/index.html.j2
            html_file_name: backend_index.html
            html_file_location: /usr/share/nginx/html
            web_server_name: Backend

        nginx_config_stream_template_enable: true
        nginx_config_stream_template:
          - template_file: stream/default.conf.j2
            conf_file_name: stream_default.conf
            conf_file_location: /etc/nginx/conf.d/stream
            network_streams:
              - listen:
                  - ip: 0.0.0.0
                    port: 9090
                    opts:
                      - udp
                proxy_pass: backend
                proxy_timeout: 3s
                proxy_connect_timeout: 1s
                proxy_protocol: false
                health_check_plus: false
            upstreams:
              - name: backend
                lb_method: least_conn
                zone_name: backend
                zone_size: 64k
                sticky_cookie: false
                servers:
                  - address: 0.0.0.0
                    port: 9091
                    weight: 1
                    health_check: max_fails=1 fail_timeout=10s
                  - address: 0.0.0.0
                    port: 9092
                    down: true
                  - address: 0.0.0.0
                    port: 9083
                    backup: true
