---
- name: "Set up SELinux"
  debug:
    msg: "Setting up SELinux"
  when: nginx_config_debug_tasks | bool

- name: "Check if SELinux is enabled"
  debug:
    msg: "You need to enable selinux, if it was disabled you need to reboot"
  when: ansible_selinux is undefined

- name: "(CentOS/RHEL) Install dependencies"
  block:
    - name: "(CentOS/RHEL 6/7) Install dependencies"
      yum:
        name:
          - policycoreutils-python
          - setools
      when: ansible_facts['distribution_major_version'] is version('8', '!=')

    - name: "(CentOS/RHEL 8) Install dependencies"
      yum:
        name:
          - libselinux-utils
          - policycoreutils
          - selinux-policy-targeted
      when: ansible_facts['distribution_major_version'] is version('8', '==')
  when: ansible_facts['os_family'] == "RedHat"

- name: "Setup permissive SELinux"
  selinux:
    state: permissive
    policy: targeted
  changed_when: false
  when: ansible_selinux.mode == "enforcing"

- name: "Allow HTTP network connection"
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: "Allow HTTP relay connection"
  seboolean:
    name: httpd_can_network_relay
    state: true
    persistent: true

- name: "Allow status ports"
  seport:
    ports: "{{ nginx_config_status_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_status_port is defined

- name: "Allow Rest API ports"
  seport:
    ports: "{{ nginx_config_rest_api_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_rest_api_port is defined

- name: "Allow specific TCP ports"
  seport:
    ports: "{{ nginx_config_selinux_tcp_ports }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: nginx_config_selinux_tcp_ports is defined

- name: "Allow specific UDP ports"
  seport:
    ports: "{{ nginx_config_selinux_udp_ports }}"
    proto: udp
    setype: http_port_t
    state: present
  when: nginx_config_selinux_udp_ports is defined

- name: "Enforce SELinux"
  selinux:
    state: enforcing
    policy: targeted
  changed_when: false
  when:
    - nginx_config_selinux_enforcing
    - ansible_selinux.mode == "permissive"

- name: "Set up SELinux"
  debug:
    msg: "Done setting up SELinux"
  when: nginx_config_debug_tasks | bool
