---
name: Ansible Galaxy Role Import
on:
  release:
    types: [published]
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-galaxy:
    name: Import role to Ansible Galaxy
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Set up Python 3
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.x

      - name: Install Ansible core
        run: pip3 install -r .github/workflows/requirements/requirements_ansible.txt

      - name: Import role releases to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
