---
name: Ansible Galaxy Role Import
on:
  release:
    types: [published]
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-galaxy:
    name: Import role to Ansible Galaxy
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python 3
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core
        run: pip3 install -r .github/workflows/requirements/requirements_ansible.txt

      - name: Import role releases to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
