---
name: Ansible Galaxy Role Import
on:
  release:
    types: [published]
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-galaxy:
    name: Import role to Ansible Galaxy
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: 3.x

      - name: Install Ansible core
        run: pip3 install -r .github/workflows/requirements/requirements_ansible.txt

      - name: Import role releases to Ansible Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
