---
name: Molecule CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags-ignore: ["**"]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python 3
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.x

      - name: Install Ansible core and Ansible Lint
        run: pip3 install -r .github/workflows/requirements/requirements_ansible_lint.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Ansible Lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
    env:
      NGINX_CRT: ${{ secrets.NGINX_CRT }}
      NGINX_KEY: ${{ secrets.NGINX_KEY }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - api_plus
          - cleanup_config
          - complete
          - complete_plus
          - default
          - push_config
          - reverse_proxy
          - stub_status
          - web_server
    needs: ansible-lint
    steps:
      - name: Check out the codebase
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python 3
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.x

      - name: Install Ansible core and Molecule
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core collection dependencies
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Molecule tests
        if: ${{ !(contains(matrix.scenario, 'plus')) || (env.NGINX_CRT != 0 && env.NGINX_KEY != 0) }}
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
