---
name: Molecule CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags-ignore: ["**"]
  merge_group:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
permissions: read-all
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core and Ansible Lint
        run: pip3 install -r .github/workflows/requirements/requirements_ansible_lint.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Ansible Lint
        run: ansible-lint --force-color

  molecule:
    name: Molecule
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - cleanup_config
          - complete
          - default
          - push_config
          - reverse_proxy
          - stub_status
          - web_server
    needs: ansible-lint
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core and Molecule
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Run Molecule tests
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1

  molecule-plus:
    name: Molecule (NGINX Plus)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - api_plus
          - complete_plus
          - entitlement_plus
    needs: ansible-lint
    permissions:
      contents: read
      id-token: write

    if: github.repository == 'nginx/ansible-role-nginx-config' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.x

      - name: Install Ansible core and Molecule
        run: pip3 install -r .github/workflows/requirements/requirements_molecule.txt

      - name: Install Ansible core collection dependencies
        run: ansible-galaxy install -r .github/workflows/requirements/requirements_collections.yml

      - name: Get plus-related secrets from Azure
        uses: nginx/ci-self-hosted/.github/actions/get-from-vault@5c3e1f8b51f66a851fdba80f70e19cf966199730
        with:
          client-id: ${{ secrets.SYSENG_CLIENT_ID }}
          tenant-id: ${{ secrets.SYSENG_TENANT_ID }}
          vault-name: ${{ secrets.NGINX_COMMON_VAULT_NAME }}
          secret-names: "nginx-pkg-certificate, nginx-pkg-key, nginx-pkg-jwt"
          env-names: "NGINX_CRT, NGINX_KEY, NGINX_JWT"

      - name: Run Molecule tests
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
